steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$symmetric-hash-417306/Tegar-Project', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$symmetric-hash-417306/Tegar-Project']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['run', 'deploy', 'customer-service', '--image', 'gcr.io/$symmetric-hash-417306/Tegar-Project', '--region', 'us-central1']
